---
title: "CRED-nf checklist summary"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    latex_engine: xelatex
classoption: landscape
geometry: margin=2cm
header-includes:
- \usepackage{fancyhdr}
- \usepackage{longtable}
- \usepackage{array}
- \fancyhf{}
- \renewcommand{\headrulewidth}{0pt}
- \fancyfoot[C]{\itshape{This report has been generated using the CRED-nf online checklist version 1.0, adapted from the CRED-nf manuscript which is freely available here https://doi.org/10.1093/brain/awaa009.}}
- \fancyhead[R]{\thepage}
- \pagestyle{fancy}
- \fancypagestyle{plain}{\pagestyle{fancy}}
params:
  title: NA
  author: NA
  email: NA
  domain1: NA
  domain2: NA
  domain3: NA
  domain4: NA
  domain5: NA
  domain6: NA
  domain7: NA
  boilers: NA
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(knitr)
library(dplyr)
escapestr <- function(x) {
  x <- gsub("\\,", "\\\\,", x)
  x <- gsub("\\.", "\\\\.", x)
  x <- gsub("\\(", "\\\\(", x)
  x <- gsub("\\)", "\\\\)", x)
  x <- gsub("\\/", "\\\\/", x)
  x <- gsub("\\?", "\\\\?", x)
  x <- gsub("\\-", "\\\\-", x)
  x <- gsub("\\:", "\\\\:", x)
  
  return(x)
}
```

```{r, echo=FALSE}
ndom <- 7

details <- vector()
for (i in 1:ndom) {
  details <- append(details, params[[paste0("domain",i)]])
}



checkIDs <- c("1a", "1b",
                "2a", "2b", "2c", " ", "2d", "2e",
                "3a", "3b", "3c", "3d", "3e",
                "4a", "4b", "4c", "4d", "4e",
                "5a", "5b", "5c",
                "6a", "6b",
                "7a"
  )

checkitem <- c("Pre-register experimental protocol and planned analyses",
               "Justify sample size",
               "Employ control group(s) or control condition(s)",
               "When leveraging experimental designs where a double-blind is possible, use a double-blind",
               "Blind those who rate the outcomes",
               "Blind those who analyse the data",
               "Examine to what extent participants and experimenters remain blinded",
               "In clinical efficacy studies, employ a standard-of-care intervention group as a benchmark for improvement",
               "Collect data on psychosocial factors",
               "Report whether participants were provided with a strategy",
               "Report the strategies participants used",
               "Report methods used for online-data processing and artifact correction",
               "Report condition and group effects for artifacts",
               "Report how the online-feature extraction was defined",
               "Report and justify the reinforcement schedule",
               "Report the feedback modality and content",
               "Collect and report all brain activity variable(s) and/or contrasts used for feedback, as displayed to experimental participants",
               "Report the hardware and software used",
               "Report neurofeedback regulation success based on the feedback signal",
               "Plot within-session and between-session regulation blocks of feedback variable(s), as well as pre-to-post resting baselines or contrasts",
               "Statistically compare the experimental condition/group to the control condition(s)/group(s) (not only each group to baseline measures)",
               "Include measures of clinical or behavioural significance, defined a priori, and describe whether they were reached",
               "Run correlational analyses between regulation success and behavioural outcomes",
               "Upload all materials, analysis scripts, code, and raw data used for analyses, as well as final values, to an open access data repository, when feasible"
               )


#table.df <- data.frame("Item.num"=checkIDs, "Checklist item"=checkitem, "Manuscript details"=details)

#indices <- list(c(1, 2), c(3,8), c(9,13), c(14,18), c(19,21), c(22,23), c(24,24))
#rownums <- c(1,3,9,14,19,22,24)

indices <- c(2,6,5,5,3,2,1)

i <- 1
while (i<=length(details)) {
  #print(nchar(details[i]))
  if (nchar(details[i]) > 1330) {
    
    # Add value to indices for relevant domain
    ind <- as.numeric(substr(checkIDs[i], 1,1))
    k <- i
    while (is.na(ind)) {
      ind <- as.numeric(substr(checkIDs[k], 1,1))
      k <- k-1
    }
    indices[ind] <- indices[ind]+1
    
    temp <- c(substr(details[i], 1, 1330),
              substr(details[i], 1331, nchar(details[i]))
              )
    details <- as.list(details)
    details[[i]] <- temp
    details <- unlist(details)
    
    checkIDs <- as.list(checkIDs)
    checkIDs[[i]] <- c(checkIDs[[i]], " ")
    checkIDs <- unlist(checkIDs)
    
    checkitem <- as.list(checkitem)
    checkitem[[i]] <- c(checkitem[[i]], " ")
    checkitem <- unlist(checkitem)
    
    i <- 1
  }
  
  i <- i+1
}

table.df <- data.frame("Item.num"=checkIDs, "Checklist item"=checkitem, "Manuscript details"=details)

```


```{r, eval=TRUE}
escboil <- escapestr(details)
# Check for matches with boilerplate
boilmatch <- as.logical(sapply(escboil, function(x) {any(grepl(x, params$boilers))}))
```


**Manuscript title:** `r params$title`  
**Corresponding Author:** `r params$author`  
**Corresponding author email:** `r params$email`  
&nbsp;




\renewcommand{\arraystretch}{1.5}
```{r, eval=TRUE}
hdr <- c("Item No.", "Checklist item", "Manuscript Details")

table.df %>%
  mutate(
    Manuscript.details = cell_spec(Manuscript.details, italic=boilmatch)
  ) %>%
  select(Item.num, Checklist.item, Manuscript.details) %>%
  kable(table.df, format="latex", longtable=TRUE, escape=FALSE,
        col.names=hdr) %>%
  kable_styling(latex_options = c("hold_position"), full_width = FALSE) %>%
  row_spec(0, bold=TRUE, font_size = 12) %>%
  column_spec(1, border_right=TRUE) %>%
  column_spec(2, border_right=TRUE, width="20em") %>%
  column_spec(3, width="40em") %>%
  kableExtra::group_rows(index=c("Pre-experiment"=indices[1], 
                                 "Control groups"=indices[2],
                                 "Control measures"=indices[3],
                                 "Feedback specifications"=indices[4],
                                 "Outcome measures - brain"=indices[5],
                                 "Outcome measures - behaviour"=indices[6],
                                 "Data storage"=indices[7]), hline_after=TRUE, hline_before = TRUE)

```